const FreeRoationActionTypes = {
    FETCH_FREE_ROTATION_START: 'FETCH_FREE_ROTATION_START',
    FETCH_FREE_ROTATION_SUCCESS: 'FETCH_FREE_ROTATION_SUCCESS',
    FETCH_FREE_ROTATION_FAILURE: 'FETCH_FREE_ROTATION_FAILURE'
}

export default FreeRoationActionTypes;