const SummonerActionTypes = {
    FETCH_CURRENT_SUMMONER_START: 'FETCH_CURRENT_SUMMONER_START',
    FETCH_CURRENT_SUMMONER_SUCCESS: 'FETCH_CURRENT_SUMMONER_SUCCESS',
    FETCH_CURRENT_SUMMONER_FAILURE: 'FETCH_CURRENT_SUMMONER_FAILURE',
    FETCH_RECENT_ARAM_START: 'FETCH_RECENT_ARAM_START',
    FETCH_RECENT_ARAM_SUCCESS: 'FETCH_RECENT_ARAM_SUCCESS',
    FETCH_RECENT_ARAM_FAILURE: 'FETCH_RECENT_ARAM_FAILURE',
    CLEAR_ARAM_DETAILS: 'CLEAR_ARAM_DETAILS'
}

export default SummonerActionTypes;